- name: Make sure git is installed
  tags: git
  apt: name=git state=installed
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Make sure unzip is installed
  tags: unzip
  apt: name=unzip state=installed
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Ensure directory exists
  action: file path={{ item }} state=directory mode=0777
  with_items:
  - "/var/log/php-fpm"